name: '${project.name}'
version: '${project.version}'
author: Nami
main: com.nami.plugin.Plugin

api-version: 1.17

commands:
    modules:
      aliases: [mdl]
    coords:
      aliases: [c]
    gamemode:
      aliases: [gm]
    chatutils:
      aliases: [cu]