name: '${project.name}'
version: '${project.version}'
author: '${author}'
main: '${mainClass}'

api-version: '${apiVersion}'

commands:
   modules:
      aliases: [mdl]
   coords:
      aliases: [c]
   gamemode:
      aliases: [gm]
   chatutils:
      aliases: [cu]